# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# BikeRoutesDataSFtemp.py
# Created on: 2017-05-26 14:29:45.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
BikeRoutesDataSF_shp = "\\\\cp-gis-svr1\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeRoutesDataSF.shp"
BikeRoutesDataSF_shp__2_ = BikeRoutesDataSF_shp
BikeRoutesDataSF_250FtBuffer_shp = "\\\\cp-gis-svr1\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeRoutesDataSF_250FtBuffer.shp"
BikeRoutesDataSF_250FtBuffer_shp__2_ = BikeRoutesDataSF_250FtBuffer_shp
BikeRoutesDataSF_HalfMileBuffer_shp = "\\\\cp-gis-svr1\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeRoutesDataSF_HalfMileBuffer.shp"
BikeRoutesDataSF_HalfMileBuffer_shp__2_ = BikeRoutesDataSF_HalfMileBuffer_shp

# Process: Add Spatial Index
arcpy.AddSpatialIndex_management(BikeRoutesDataSF_shp, "0", "0", "0")

# Process: Add Spatial Index (2)
arcpy.AddSpatialIndex_management(BikeRoutesDataSF_250FtBuffer_shp, "0", "0", "0")

# Process: Add Spatial Index (3)
arcpy.AddSpatialIndex_management(BikeRoutesDataSF_HalfMileBuffer_shp, "0", "0", "0")

