"C:\ETLs\TIM\TIMUpdates\New ETLs\BayAreaBikeShare_in_gdb.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\BikeparkingDataSF_in_gdb.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\BikeRoutesDataSF_in_gdb.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\CurbCutRestrictions_in_gdb.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\CurbRampsDataSF_in_gdb.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\GreenConnectionsBSP_in_gdb.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\KeyWalkingStreets.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\mitigation_measures.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\MUNIStopsAndRoutes_in_gdb.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\TrafficCalmingDataSF_in_gdb.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\Transbase_1.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\Transbase_2v2.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\TransitStopsDataSF_in_gdb.py"
"C:\ETLs\TIM\TIMUpdates\New ETLs\TruckRoutesDataSF.py"


