C:\ETLs\TIM\TIMUpdates\BayAreaBikeShare_v2.py
C:\ETLs\TIM\TIMUpdates\BikeRoutesDataSF.py
C:\ETLs\TIM\TIMUpdates\BSP_GreenConnections.py
C:\ETLs\TIM\TIMUpdates\DataSF_Bikeparking.py
C:\ETLs\TIM\TIMUpdates\DataSF_CurbRamps.py
C:\ETLs\TIM\TIMUpdates\DataSF_TrafficCalming.py
C:\ETLs\TIM\TIMUpdates\DataSF_TransitStops.py
C:\ETLs\TIM\TIMUpdates\DataSF_TruckRoutes.py
C:\ETLs\TIM\TIMUpdates\MUNIStopsAndRoutes.py
C:\ETLs\TIM\TIMUpdates\transbase_1.py
C:\ETLs\TIM\TIMUpdates\transbase_2v2.py
C:\ETLs\TIM\TIMUpdates\CurbCutRestrictions.py
C:\ETLs\TIM\TIMUpdates\keyWalkingStreets.py
C:\ETLs\TIM\TIMUpdates\mitigation_measures.py
C:\ETLs\TIM\TIMUpdates\UpdateSpatialIndexes.py
c:\ETLs\TIM\SendToAmazon.py