# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# UpdateSpatialIndexes.py
# Created on: 2017-04-24 14:58:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
MUNIRoutes_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\MUNIRoutes.shp"
MUNIRoutes_shp__2_ = MUNIRoutes_shp
MUNIStops_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\MUNIStops.shp"
MUNIStops_shp__2_ = MUNIStops_shp
betterstreetsbuffer_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\betterstreetsbuffer.shp"
betterstreetsbuffer_shp__2_ = betterstreetsbuffer_shp
BetterStreetsPlan_TIM_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\BetterStreetsPlan_TIM.shp"
BetterStreetsPlan_TIM_shp__2_ = BetterStreetsPlan_TIM_shp
bikecollisions_party_bike_fatal_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\bikecollisions_party_bike_fatal.shp"
bikecollisions_party_bike_fatal_shp__2_ = bikecollisions_party_bike_fatal_shp
bikecollisions_party_bike_fatal_shp__3_ = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\bikecollisions_party_bike_fatal.shp"
bikecollisions_party_bike_fatal_shp__4_ = bikecollisions_party_bike_fatal_shp__3_
BikeParking_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeParking.shp"
BikeParking_shp__2_ = BikeParking_shp
BikeParkingBuffer250ft_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeParkingBuffer250ft.shp"
BikeParkingBuffer250ft_shp__2_ = BikeParkingBuffer250ft_shp
bikeroutebuffer_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\bikeroutebuffer.shp"
bikeroutebuffer_shp__2_ = bikeroutebuffer_shp
BikeRoutesDataSF_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeRoutesDataSF.shp"
BikeRoutesDataSF_shp__2_ = BikeRoutesDataSF_shp
BikeRoutesDataSF_250FtBuffer_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeRoutesDataSF_250FtBuffer.shp"
BikeRoutesDataSF_250FtBuffer_shp__2_ = BikeRoutesDataSF_250FtBuffer_shp
BikeRoutesDataSF_HalfMileBuffer_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeRoutesDataSF_HalfMileBuffer.shp"
BikeRoutesDataSF_HalfMileBuffer_shp__2_ = BikeRoutesDataSF_HalfMileBuffer_shp
BikeShareStations_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeShareStations.shp"
BikeShareStations_shp__2_ = BikeShareStations_shp
BikeShareStations_buffer05mile_shp = "C:\\arcgisserver\\DataAndMXDs\\TIMReady\\BikeShareStations_buffer05mile.shp"
BikeShareStations_buffer05mile_shp__2_ = BikeShareStations_buffer05mile_shp


myStartDate = str(datetime.date.today())
myStartTime = time.clock()
theStartTime = time.ctime()
print theStartTime


# thisfile = os.path.realpath(__file__)
file = open("C:/ETLs/TIM/TIMUpdates/Logs/" + myStartDate + "UpdateSpatialIndexes" + ".txt", "w")
file.write(theStartTime + "\n")


try: 
    arcpy.AddSpatialIndex_management(MUNIRoutes_shp, "0", "0", "0")
    print "Refreshed spatial indexes for MUNIRoutes_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for MUNIRoutes_shp"+ "\n")
except:
    print "Could not refresh spatial index for MUNIRoutes_shp"

try:
    arcpy.AddSpatialIndex_management(MUNIStops_shp, "0", "0", "0")
    print "Refreshed spatial indexes for MUNIStops_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for MUNIStops_shp"+ "\n")
except:
    print "Could not refresh spatial index for MUNIStops_shp"

try:
    arcpy.AddSpatialIndex_management(betterstreetsbuffer_shp, "0", "0", "0")
    print "Refreshed spatial indexes for betterstreetsbuffer_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for betterstreetsbuffer_shp"+ "\n")
except:
    print "Could not refresh spatial index for betterstreetsbuffer_shp"

try:
    arcpy.AddSpatialIndex_management(BetterStreetsPlan_TIM_shp, "0", "0", "0")
    print "Refreshed spatial indexes for BetterStreetsPlan_TIM_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for BetterStreetsPlan_TIM_shp"+ "\n")
except:
    print "Could not refresh spatial index for BetterStreetsPlan_TIM_shp"
try:
    arcpy.AddSpatialIndex_management(bikecollisions_party_bike_fatal_shp, "0", "0", "0")
    print "Refreshed spatial indexes for bikecollisions_party_bike_fatal_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for bikecollisions_party_bike_fatal_shp"+ "\n")
except:
    print "Could not refresh spatial index for bikecollisions_party_bike_fatal_shp"
try:
    arcpy.AddSpatialIndex_management(bikecollisions_party_bike_fatal_shp__3_, "0", "0", "0")
    print "Refreshed spatial indexes for bikecollisions_party_bike_fatal_shp__3_"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for bikecollisions_party_bike_fatal_shp__3_"+ "\n")
except:
    print "Could not refresh spatial index for bikecollisions_party_bike_fatal_shp__3_"
try:
    arcpy.AddSpatialIndex_management(BikeParking_shp, "0", "0", "0")
    print "Refreshed spatial indexes for BikeParking_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for BikeParking_shp"+ "\n")
except:
    print "Could not refresh spatial index for BikeParking_shp"
try:
    arcpy.AddSpatialIndex_management(BikeParkingBuffer250ft_shp, "0", "0", "0")
    print "Refreshed spatial indexes for BikeParkingBuffer250ft_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for BikeParkingBuffer250ft_shp"+ "\n")
except:
    print "Could not refresh spatial index for BikeParkingBuffer250ft_shp"
try:
    arcpy.AddSpatialIndex_management(bikeroutebuffer_shp, "0", "0", "0")
    print "Refreshed spatial indexes for bikeroutebuffer_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for bikeroutebuffer_shp"+ "\n")
except:
    print "Could not refresh spatial index for bikeroutebuffer_shp"
try:
    arcpy.AddSpatialIndex_management(BikeRoutesDataSF_shp, "0", "0", "0")
    print "Refreshed spatial indexes for BikeRoutesDataSF_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for BikeRoutesDataSF_shp"+ "\n")
except:
    print "Could not refresh spatial index for BikeRoutesDataSF_shp"
try:
    arcpy.AddSpatialIndex_management(BikeRoutesDataSF_250FtBuffer_shp, "0", "0", "0")
    print "Refreshed spatial indexes for BikeRoutesDataSF_250FtBuffer_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for BikeRoutesDataSF_250FtBuffer_shp"+ "\n")
except:
    print "Could not refresh spatial index for BikeRoutesDataSF_250FtBuffer_shp"
try:
    arcpy.AddSpatialIndex_management(BikeRoutesDataSF_HalfMileBuffer_shp, "0", "0", "0")
    print "Refreshed spatial indexes for BikeRoutesDataSF_HalfMileBuffer_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for BikeRoutesDataSF_HalfMileBuffer_shp"+ "\n")
except:
    print "Could not refresh spatial index for BikeRoutesDataSF_HalfMileBuffer_shp"
try:
    arcpy.AddSpatialIndex_management(BikeShareStations_shp, "0", "0", "0")
    print "Refreshed spatial indexes for BikeShareStations_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for BikeShareStations_shp"+ "\n")
except:
    print "Could not refresh spatial index for BikeShareStations_shp"
try:
    arcpy.AddSpatialIndex_management(BikeShareStations_buffer05mile_shp, "0", "0", "0")
    print "Refreshed spatial indexes for BikeShareStations_buffer05mile_shp"
    file.write(str(time.ctime()) +": Refreshed spatial indexes for BikeShareStations_buffer05mile_shp"+ "\n")
except:
    print "Could not refresh spatial index for BikeShareStations_buffer05mile_shp"

